# Generated by Django 4.1.7 on 2023-05-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40, verbose_name='Nombre')),
                ('ap', models.CharField(max_length=40, verbose_name='Apellido')),
                ('dir', models.TextField(max_length=40, null=True, verbose_name='Direcció')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='foto')),
            ],
        ),
    ]
